import type { AppProps } from "next/app";
import Head from "next/head";
import { Header } from "../components/Global/Header";
import { Footer } from "../components/Global/Footer";
import { AuthContextProvider } from "../contexts/AuthContext";
import "../styles/styles.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <AuthContextProvider>
      <Head>
        <title>Femina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/Favicon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Header />
        <Component {...pageProps} />
        <Footer />
      </div>
    </AuthContextProvider>
  );
}

export default MyApp;
