import type { AppProps } from "next/app";
import Head from "next/head";
import {Header} from "../components/Global/Header"
import '../styles/styles.css';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Femina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />        
      </Head>
      <div>
        <Header/>
        <Component {...pageProps} />
      </div>
    </>
  );
}

export default MyApp;
