import type { AppProps } from "next/app";
import Head from "next/head";
import { Header } from "../components/Global/Header";
import "../styles/styles.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Femina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/Favicon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Header />
        <Component {...pageProps} />
      </div>
    </>
  );
}

export default MyApp;
